version: 0.1.0

name: Customer Repository Stack
description: This is a stack to demonstrate how Stacks could be used for initializing repositories framing customer engagements.

inputs:
  - name: INIT_SAMPLE_ENGAGEMENT
    description: Whether to initialize sample engagement.
    default: no
    validvalues:
      - yes
      - no

init:
  uses: init.yml