version: 0.1.0

name: Customer Repository Stack
description: This is a stack to demonstrate how Stacks could be used for initializing repositories framing customer engagements.
branding:
  color: black

inputs:
  - name: customer_name
    description: Name of customer this repository is for.
    required: true

  - name: init_engagements
    description: Whether to initialize engagements.
    type: boolean
    default: "true"

  - name: debug
    description: Whether to display debug information.
    type: boolean
    default: "false"

init:
  uses: init.yml
